### PR TITLE
Replace `piscina` with `tinypool`

### LINKED ISSUE #59: Evaluate using tinypool over piscina
[tinypool](https://github.com/tinylibs/tinypool) is a lightweight fork of piscina with useless features like NAPI removed, it might be a good fit for this module.

### PR DESCRIPTION
**Pull request by fisker**
Fixes #59

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Do you have any before/after for how long this takes to run Prettier's tests?

**Comment by fisker** [comment]
Since Prettier tests runs with `--runInBand`, so there is nothing to compare at all. I'll make it work for `--maxWorkers` first.

**Comment by fisker** [comment]
Here is the result:

With `piscina` (1m 27s)

https://github.com/nicolo-ribaudo/jest-light-runner/actions/runs/7013294881/job/19079198358?pr=82

With `tinypool` (1m 28s)

https://github.com/nicolo-ribaudo/jest-light-runner/actions/runs/7013320207/job/19079264994?pr=82

**Comment by nicolo-ribaudo** [comment]
Given that this does introduce perf regressions, I'm accepting the change given that it reduces the number of deps.

**Comment by nicolo-ribaudo** [comment]
Let me know if this is ready to merge, then I'll update the Babel tests :)

**Comment by fisker** [comment]
I think it's ready.

**Pull request merged**
