### PR TITLE
Use Jest 30.0.0-alpha.1

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
I'm testing this in Babel, it looks like there is a Node.js bug but I'm updating it here to simplify testing.

@fisker Could you try if it causes any problem in Prettier?

cc @SimenB

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Prettier failures are good and caused by https://github.com/jestjs/jest/pull/13965.

I'll release this PR as a pre-release.

**Comment by SimenB** [comment]
> it looks like there is a Node.js bug

👀

**Comment by nicolo-ribaudo** [comment]
It was a Node.js internal assertion (from JS, not from C++), but it doesn't happen anymore 😅 
Also, I had no stack trace.

**Comment by SimenB** [comment]
> but it doesn't happen anymore 😅

Fixed! 😀

**Pull request merged**
