### PR TITLE
Support Node.js v12

### PR DESCRIPTION
**Pull request by fisker**
Prettier still support Node.js 12 :(

### CODE REVIEW

**Comment by SimenB** [comment]
12 is eol later this week fwiw

**Comment by fisker** [comment]
I know... We even support Node.js 10 in main branch. 😄

**Comment by SimenB** [comment]
Jest 28 will be released today. Dropping 10, but keeping 12 😀

**Comment by fisker** [comment]
FYI: Node.js v4 EOL 2018-04-30, we drop support 2020-03-21 https://prettier.io/blog/2020/03/21/2.0.0.html#breaking-changes

**Comment by nicolo-ribaudo** [comment]
We also needs Node.js 12 support for Babel tests! I wanted to fix this today, so thanks for the PR!

**Review by nicolo-ribaudo — APPROVED** [review]

**Pull request merged**
